/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.models.detalleCompra;
import com.mycompany.models.precioActualizado;
import com.mycompany.superluna.DAOprecioActualizadoImp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abarrotesluna
 */
public class ActualizarPrecios extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarPrecios
     */
    private DefaultTableModel modelo;

    public ActualizarPrecios() {
        initComponents();
        inicializarTabla();
        cargarPendientes();
        jTable1.getSelectionModel().addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting()) {

        int fila = jTable1.getSelectedRow();
        if (fila == -1) return;

        txtCodigo.setText(modelo.getValueAt(fila, 2).toString());
        txtPrecioCompra.setText(modelo.getValueAt(fila, 4).toString());
        txtPrecioAnterior.setText(modelo.getValueAt(fila, 4).toString());
        txtNuevoPrecio.setText("");
        txtNuevoPrecio.requestFocus();
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNuevoPrecio = new javax.swing.JLabel();
        lblPrecioCompra = new javax.swing.JLabel();
        txtNuevoPrecio = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        lblPrecioAnterior = new javax.swing.JLabel();
        txtPrecioAnterior = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        jbActualizar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(225, 124, 22));

        jLabel1.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ACTUALIZAR PRECIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
        );

        lblNuevoPrecio.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblNuevoPrecio.setText("NUEVO PRECIO");

        lblPrecioCompra.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblPrecioCompra.setText("PRECIO DE COMPRA");

        txtNuevoPrecio.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtNuevoPrecio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNuevoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoPrecioActionPerformed(evt);
            }
        });

        txtPrecioCompra.setEditable(false);
        txtPrecioCompra.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtPrecioCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCompraActionPerformed(evt);
            }
        });

        lblPrecioAnterior.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblPrecioAnterior.setText("PRECIO ANTERIOR");

        txtPrecioAnterior.setEditable(false);
        txtPrecioAnterior.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtPrecioAnterior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPrecioAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioAnteriorActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtCodigo.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblCodigo.setText("CODIGO DE BARRAS");

        jbActualizar.setBackground(new java.awt.Color(102, 102, 255));
        jbActualizar.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/guardar.png"))); // NOI18N
        jbActualizar.setText("ACTUALIZAR");
        jbActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbActualizar.setIconTextGap(10);
        jbActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbActualizarMouseClicked(evt);
            }
        });
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbLimpiar.setBackground(new java.awt.Color(51, 153, 255));
        jbLimpiar.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        jbLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/limpiar.png"))); // NOI18N
        jbLimpiar.setText("LIMPIAR");
        jbLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbLimpiar.setIconTextGap(10);
        jbLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbLimpiarMouseClicked(evt);
            }
        });
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(lblPrecioAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioAnterior))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPrecioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(txtPrecioCompra)
                            .addComponent(lblNuevoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNuevoPrecio))
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(txtNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrecioAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(txtPrecioAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void inicializarTabla() {
    modelo = new DefaultTableModel(
        new String[]{
            "Id Compra",
            "Id Detalle",
            "Código",
            "Cantidad",
            "Precio Compra"
        }, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    jTable1.setModel(modelo);
}
    private void cargarPendientes() {
    try {
        modelo.setRowCount(0); // limpiar tabla

        DAOprecioActualizadoImp dao = new DAOprecioActualizadoImp();
        dao.conectar(); // si tu DAO hereda de Conexion

        for (detalleCompra d : dao.listarPreciosSinActualizar()) {
            modelo.addRow(new Object[]{
                d.getIdCompra(),
                d.getIdCompraDetalle(),
                d.getIdProducto(),
                d.getCantidad(),
                d.getPrecioUni()
            });
        }

        dao.cerrarConexion();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            this,
            "Error al cargar pendientes\n" + e.getMessage(),
            "ERROR",
            JOptionPane.ERROR_MESSAGE
        );
    }
}
    private void limpiarFormulario() {
    txtCodigo.setText("");
    txtPrecioCompra.setText("");
    txtPrecioAnterior.setText("");
    txtNuevoPrecio.setText("");
}


    private void txtNuevoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoPrecioActionPerformed
        txtPrecioCompra.requestFocus();   // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoPrecioActionPerformed

    private void txtPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCompraActionPerformed
    
    }//GEN-LAST:event_txtPrecioCompraActionPerformed

    private void txtPrecioAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioAnteriorActionPerformed
        
    }//GEN-LAST:event_txtPrecioAnteriorActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void jbActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbActualizarMouseClicked
     int fila = jTable1.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this,
            "Selecciona un registro de la tabla",
            "Aviso",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (txtNuevoPrecio.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Ingresa el nuevo precio",
            "Aviso",
            JOptionPane.WARNING_MESSAGE
        );
        txtNuevoPrecio.requestFocus();
        return;
    }

    try {
        // ===== Datos desde la tabla =====
        int idCompra = (int) modelo.getValueAt(fila, 0);
        int idDetalleCompra = (int) modelo.getValueAt(fila, 1);
        String idProducto = modelo.getValueAt(fila, 2).toString();
        double precioCompra = ((Number) modelo.getValueAt(fila, 4)).doubleValue();

        // ===== Datos desde la UI =====
        double precioAnterior = Double.parseDouble(txtPrecioAnterior.getText());
        double nuevoPrecio = Double.parseDouble(txtNuevoPrecio.getText());

        if (nuevoPrecio <= 0) {
            throw new NumberFormatException();
        }

        // ===== USO DEL MODELO (AQUÍ ESTÁ LA RESPUESTA A TU DUDA) =====
        precioActualizado pa = new precioActualizado();
        pa.setIdProducto(idProducto);
        pa.setPrecioAnterior(precioAnterior);
        pa.setPrecioCompra(precioCompra);
        pa.setNuevoPrecio(nuevoPrecio);
        pa.setIdCompra(idCompra);
        pa.setIdDetalleCompra(idDetalleCompra);
        pa.setFechaActualizacion(
            new java.sql.Timestamp(System.currentTimeMillis())
        );

        // ===== DAO =====
        DAOprecioActualizadoImp dao = new DAOprecioActualizadoImp();
        dao.conectar();
        dao.registrar(pa);
        dao.cerrarConexion();

        // ===== UI =====
        modelo.removeRow(fila);
        limpiarFormulario();

        JOptionPane.showMessageDialog(this,
            "Precio actualizado correctamente",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE
        );

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Nuevo precio inválido",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
        txtNuevoPrecio.requestFocus();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error al actualizar precio\n" + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }    
    }//GEN-LAST:event_jbActualizarMouseClicked

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed

    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLimpiarMouseClicked
        
    }//GEN-LAST:event_jbLimpiarMouseClicked

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNuevoPrecio;
    private javax.swing.JLabel lblPrecioAnterior;
    private javax.swing.JLabel lblPrecioCompra;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNuevoPrecio;
    private javax.swing.JTextField txtPrecioAnterior;
    private javax.swing.JTextField txtPrecioCompra;
    // End of variables declaration//GEN-END:variables
}
