/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOproductos;
import com.mycompany.models.compras;
import com.mycompany.models.detalleCompra;
import com.mycompany.superluna.DAOproductosImp;
import com.mycompany.models.productos;
import com.mycompany.superluna.BuscarProductoDialog;
import com.mycompany.superluna.Servicios;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author luis-alberto
 */
public class Compras extends javax.swing.JPanel {
    productos Producto;
    DefaultTableModel modelo;
    double total = 0;
    /**
     * Creates new form Compras
     */
    public Compras() {
        initComponents();
        modelo = (DefaultTableModel) jtListaCompra.getModel();
        modelo.setRowCount(0);
        limpiarCampos();
        registrarTeclaF2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcTipoProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaCompra = new javax.swing.JTable();
        txtCodigoBarras = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblPrecioUni = new javax.swing.JLabel();
        txtPrecioUni = new javax.swing.JTextField();
        lblCodigo1 = new javax.swing.JLabel();
        lblPrecioUni1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        lblPrecioUni2 = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        lblPrecioUni3 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(225, 124, 22));

        jLabel1.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPRAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
        );

        jcTipoProducto.setFont(new java.awt.Font("Roboto SemiBold", 0, 18)); // NOI18N
        jcTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABARROTES", "PANADERIA", "VERDURAS", "CREMERIA", "BULTOS", " ", " " }));
        jcTipoProducto.setEnabled(false);

        jtListaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO DE BARRAS", "TIPO DE PRODUCTO", "NOMBRE", "PRECIO UNITARIO", "CANTIDAD", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaCompra);

        txtCodigoBarras.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtCodigoBarras.setBorder(null);
        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasActionPerformed(evt);
            }
        });
        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyPressed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblCodigo.setText("TIPO DE PRODUCTO");

        lblPrecioUni.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblPrecioUni.setText("PRECIO UNITARIO");

        txtPrecioUni.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtPrecioUni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPrecioUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioUniActionPerformed(evt);
            }
        });
        txtPrecioUni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioUniKeyPressed(evt);
            }
        });

        lblCodigo1.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblCodigo1.setText("CÓDIGO DE BARRAS");

        lblPrecioUni1.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblPrecioUni1.setText("CANTIDAD");

        txtCantidad.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtCantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        txtTotal.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtTotal.setEnabled(false);

        lblPrecioUni2.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblPrecioUni2.setText("TOTAL");

        jbEliminar.setBackground(new java.awt.Color(255, 102, 102));
        jbEliminar.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        jbEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/eliminar.png"))); // NOI18N
        jbEliminar.setText("ELIMINAR");
        jbEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbEliminar.setIconTextGap(10);
        jbEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEliminarMouseClicked(evt);
            }
        });
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbAgregar.setBackground(new java.awt.Color(70, 220, 70));
        jbAgregar.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        jbAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/agregar.png"))); // NOI18N
        jbAgregar.setText("AGREGAR");
        jbAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbAgregar.setIconTextGap(10);
        jbAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAgregarMouseClicked(evt);
            }
        });
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbGuardar.setBackground(new java.awt.Color(102, 102, 255));
        jbGuardar.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/guardar.png"))); // NOI18N
        jbGuardar.setText("GUARDAR");
        jbGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbGuardar.setIconTextGap(10);
        jbGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbGuardarMouseClicked(evt);
            }
        });

        lblPrecioUni3.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblPrecioUni3.setText("SUBTOTAL");

        txtSubtotal.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        txtSubtotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSubtotal.setEnabled(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblNombre.setText("NOMBRE");

        lblNombre1.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 18)); // NOI18N
        lblNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrecioUni2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcTipoProducto, javax.swing.GroupLayout.Alignment.CENTER, 0, 250, Short.MAX_VALUE)
                                    .addComponent(jbAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(lblCodigo1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(lblPrecioUni1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioUni)
                                    .addComponent(lblPrecioUni, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                            .addComponent(txtSubtotal)
                            .addComponent(lblPrecioUni3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(94, 94, 94))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioUni1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioUni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jcTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioUni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioUni3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioUni2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCampos() {
    txtCodigoBarras.setText("");
    txtCantidad.setText("0");
    txtPrecioUni.setText("0");
    txtSubtotal.setText("0");
    lblNombre1.setText("");
    Producto = null;
}
    private void registrarTeclaF2() {

    this.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)
        .put(KeyStroke.getKeyStroke("F2"), "buscarProducto");

    this.getActionMap().put("buscarProducto", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            abrirBusqueda();
        }
    });
}
    private void abrirBusqueda() {

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

        BuscarProductoDialog dialog = new BuscarProductoDialog(frame);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true); 

        productos p = dialog.getProductoSeleccionado();
        if (p != null) {
            Producto = p;
            txtCodigoBarras.setText(p.getIdProducto());
            lblNombre1.setText(p.getNombreProducto());

            
            txtCantidad.setEnabled(true);
            txtCantidad.requestFocusInWindow();
        }

        
        this.requestFocusInWindow();
    }




    private void mostrarCampos(productos Prod){
    if(Prod != null){
        Producto =  Prod;
        switch(Producto.getIdTipo()){
            case 1:
                jcTipoProducto.setSelectedIndex(0);
                break;
            case 2:
                jcTipoProducto.setSelectedIndex(1);
                break;
            case 3:
                jcTipoProducto.setSelectedIndex(2);
                break;
            case 4:
                jcTipoProducto.setSelectedIndex(3);
                break;
            case 5:
                jcTipoProducto.setSelectedIndex(4);
                break;
        }
        lblNombre1.setText(Producto.getNombreProducto());
    }
    }


    private void jbAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAgregarMouseClicked
        if (Producto == null) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto");
        return;
    }

    int cantidad = Integer.parseInt(txtCantidad.getText());
    double precio = Double.parseDouble(txtPrecioUni.getText());
    double subtotal = precio * cantidad;

    modelo.addRow(new Object[]{
        Producto.getIdProducto(),
        jcTipoProducto.getSelectedItem(),
        Producto.getNombreProducto(),
        precio,
        cantidad,
        subtotal
    });

    total += subtotal;
    txtTotal.setText(String.valueOf(total));

    limpiarCampos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAgregarMouseClicked

    private void jbEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEliminarMouseClicked
    int fila = jtListaCompra.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto de la lista");
        return;
    }

    double subtotal = (double) modelo.getValueAt(fila, 5);
    total -= subtotal;

    modelo.removeRow(fila);
    txtTotal.setText(String.valueOf(total));
            // TODO add your handling code here:
    }//GEN-LAST:event_jbEliminarMouseClicked

    private void jbGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGuardarMouseClicked
     if (modelo.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No hay productos en la compra");
        return;
    }

    String efectivoStr = JOptionPane.showInputDialog(
        this,
        "¿Con cuánto efectivo pagó?",
        "Pago",
        JOptionPane.QUESTION_MESSAGE
    );

    if (efectivoStr == null) return;

    double efectivo;
    try {
        efectivo = Double.parseDouble(efectivoStr);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Monto inválido");
        return;
    }

    if (efectivo < total) {
        JOptionPane.showMessageDialog(this, "Efectivo insuficiente");
        return;
    }

    double cambio = efectivo - total;

    try {
        compras compra = new compras();
        compra.setTotalCompra(total);
        compra.setEfectivo(efectivo);
        compra.setCambio(cambio);
        compra.setFechaCompra(new java.sql.Timestamp(System.currentTimeMillis()));

        List<detalleCompra> detalles = new ArrayList<>();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            detalleCompra d = new detalleCompra();
            d.setIdProducto(modelo.getValueAt(i, 0).toString());
            d.setSubtotalCompra((double) modelo.getValueAt(i, 5));
            d.setCantidad((int)modelo.getValueAt(i, 4));
            d.setPrecioUni((double) modelo.getValueAt(i, 3));
            detalles.add(d);
        }

        Servicios servicio = new Servicios();
        servicio.guardarCompra(compra, detalles);

        JOptionPane.showMessageDialog(this,
                "Compra realizada\nCambio: $" + cambio);

        modelo.setRowCount(0);
        total = 0;
        txtTotal.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Error al guardar compra\n" + e.getMessage(),
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }   // TODO add your handling code here:
    }//GEN-LAST:event_jbGuardarMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtCodigoBarrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarrasKeyPressed

    private void txtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasActionPerformed
    
    try{
        String codigoBarras = txtCodigoBarras.getText();
        DAOproductos daoProd = new DAOproductosImp();
        try{
            mostrarCampos(daoProd.obtenerProductoId(codigoBarras));
            txtCantidad.requestFocus();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Producto no encontrado","ERROR",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }catch (Exception e) {
           JOptionPane.showMessageDialog(this,"Ingrese un valor válido","ERROR",javax.swing.JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_txtCodigoBarrasActionPerformed

    private void txtPrecioUniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioUniKeyPressed
    
    }//GEN-LAST:event_txtPrecioUniKeyPressed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
    
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
    int cantidad;
    double precio,subtotal;
    
    try {
        cantidad = Integer.parseInt(txtCantidad.getText());
        precio = Double.parseDouble(txtPrecioUni.getText());
        subtotal = cantidad*precio;
        txtSubtotal.setText(Double.toString(subtotal));
        if (cantidad <= 0) throw new NumberFormatException();
        txtPrecioUni.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cantidad inválida");
        return;
    }
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtPrecioUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioUniActionPerformed
    int cantidad;
    double precio,subtotal;
    
    try {
        cantidad = Integer.parseInt(txtCantidad.getText());
        precio = Double.parseDouble(txtPrecioUni.getText());
        subtotal = cantidad*precio;
        txtSubtotal.setText(Double.toString(subtotal));
            if (precio <= 0) throw new NumberFormatException();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Solo se permiten numeros");
            return;
        }
    }//GEN-LAST:event_txtPrecioUniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcTipoProducto;
    private javax.swing.JTable jtListaCompra;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPrecioUni;
    private javax.swing.JLabel lblPrecioUni1;
    private javax.swing.JLabel lblPrecioUni2;
    private javax.swing.JLabel lblPrecioUni3;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtPrecioUni;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
