/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOusuarios;
import com.mycompany.models.usuarios;
import com.mycompany.superluna.DAOusuariosImp;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis-alberto
 */
public class Usuarios extends javax.swing.JPanel {

    usuarios modificarUsuario;
    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        txtNombre.requestFocus();
        loadUsuarios();
    }
    private void mostrarCampos(usuarios usuario){
    if(usuario != null){
    modificarUsuario=usuario;
    txtNombre.setText(usuario.getNombreUsuario());
    txtIdentificador.setText(Integer.toString(usuario.getIdUsuario()));
    txtContra.setText(usuario.getPass());
    if(usuario.getIdTipoUsuario()==1)
    {
    cbxTipo.setSelectedIndex(0);
    }else if(usuario.getIdTipoUsuario()==2){
    cbxTipo.setSelectedIndex(1);
    }else{
    cbxTipo.setSelectedIndex(2);
    }
    }
    }
    private void loadUsuarios(){
        try {
            DAOusuarios daoUs = new DAOusuariosImp();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            daoUs.listar().forEach((u) -> model.addRow(new Object[]{u.getIdUsuario(),u.getNombreUsuario(),u.getIdTipoUsuario(),u.getPass()}));
        } catch (Exception e) {
        }
    }
    private void limpiarCAmpos(){
    txtContra.setText("");
    txtNombre.setText("");
    txtIdentificador.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblIdentificador = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        lblContra = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        btnConsultar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(225, 124, 22));

        lblVista.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 1, 36)); // NOI18N
        lblVista.setForeground(new java.awt.Color(255, 255, 255));
        lblVista.setText("USUARIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblVista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblVista)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "NOMBRE", "TIPO DE USUARIO", "CONTRASEÑA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        lblIdentificador.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblIdentificador.setText("IDENTIFICADOR");

        txtIdentificador.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        txtIdentificador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtIdentificador.setEnabled(false);

        lblNombre.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblNombre.setText("NOMBRE");

        txtNombre.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 153, 51));
        btnModificar.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/editar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificar.setIconTextGap(10);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(70, 220, 70));
        btnAgregar.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/agregar.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar.setIconTextGap(10);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(102, 102, 255));
        btnConsultar.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/buscar.png"))); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsultar.setIconTextGap(10);
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });

        lblTipo.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblTipo.setText("TIPO DE USUARIO");

        cbxTipo.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Gerente", "Vendedor" }));
        cbxTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblContra.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 24)); // NOI18N
        lblContra.setText("CONTRASEÑA");

        txtContra.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        txtContra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtBuscar.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        btnConsultar1.setBackground(new java.awt.Color(102, 102, 255));
        btnConsultar1.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        btnConsultar1.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/limpiar.png"))); // NOI18N
        btnConsultar1.setText("LIMPIAR");
        btnConsultar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsultar1.setIconTextGap(10);
        btnConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(183, 183, 183)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdentificador, javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTipo, javax.swing.GroupLayout.Alignment.CENTER, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIdentificador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre)
                                    .addComponent(lblContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtContra)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
    com.mycompany.models.usuarios usuario = new com.mycompany.models.usuarios();
    if (txtContra.getText().equals("")||txtNombre.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this, "Ingrese valores válidos","AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        txtNombre.requestFocus();
    }else{
    String nombre = txtNombre.getText();
    String pass = txtContra.getText();
    int tipo;
        Object selectedItem = cbxTipo.getSelectedItem();
if (selectedItem == null) {
    throw new IllegalStateException("No se ha seleccionado ningún tipo.");
}

switch (selectedItem.toString()) {
    case "Gerente":
        tipo = 2;
        break;
    case "Administrador":
        tipo = 1;
        break;
    case "Vendedor":
        tipo = 3;
        break;
    default:
        throw new IllegalArgumentException("Tipo desconocido: " + selectedItem);
}
    
    usuario.setNombreUsuario(nombre);
    usuario.setPass(pass);
    usuario.setIdTipoUsuario(tipo);
    
        try {
            DAOusuarios dao = new DAOusuariosImp();
            dao.registrar(usuario);
            limpiarCAmpos();
            JOptionPane.showMessageDialog(this, "Se ha registrado el usuario correctamente","OPERACION EXITOSA",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guardar los datos","ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
     int tipo=3;
        try{
            Integer.parseInt(txtIdentificador.getText());
    
     modificarUsuario.setNombreUsuario(txtNombre.getText());
     modificarUsuario.setPass(txtContra.getText());
      Object selectedItem = cbxTipo.getSelectedItem();
if (selectedItem == null) {
    throw new IllegalStateException("No se ha seleccionado ningún tipo.");
}

switch (selectedItem.toString()) {
    case "Gerente":
        tipo = 2;
        break;
    case "Administrador":
        tipo = 1;
        break;
    case "Vendedor":
        tipo = 3;   
        break;
    default:
        throw new IllegalArgumentException("Tipo desconocido: " + selectedItem);
}
modificarUsuario.setIdTipoUsuario(tipo);
            try {
                DAOusuarios dao = new DAOusuariosImp();
                dao.modificar(modificarUsuario);
                JOptionPane.showMessageDialog(this, "Se ha actualizado el usuario correctamente","OPERACION EXITOSA",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al modificar los datos","ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }finally{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Esto elimina todas las filas de la tabla.
            loadUsuarios();
            
            
            }
     }
        catch (Exception e){
         JOptionPane.showMessageDialog(this,"Se debe seleccionar un usuario primero","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
     
        }

    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        try {
            int idUsuario = Integer.parseInt(txtBuscar.getText()) ;
            DAOusuarios dao = new DAOusuariosImp();
            try {
                mostrarCampos(dao.getUserById(idUsuario));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Usuario no encontrado","ERROR",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,"Ingrese un valor válido","ERROR",javax.swing.JOptionPane.ERROR_MESSAGE); 
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        txtContra.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(jTable1.getSelectedRow() > -1){
    int idUsuario = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
    DAOusuarios dao = new DAOusuariosImp();
            try {
                mostrarCampos(dao.getUserById(idUsuario));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Error al mostrar los datos","ERROR",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
    
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar1MouseClicked
    limpiarCAmpos();       // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblVista;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
